version: '3'
services:
  image-uploader:
    build: .
    container_name: image-uploader
    ports:
      - "8600:8600"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    environment:
      - NODE_ENV=production 